services:
  web:
    image: php:8.2-apache
    container_name: php_web_server
    ports:
      - "5200:80"
    volumes:
      - ./proyecto-final-vii:/var/www/html
      - ./proyecto-final-vii/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - app-network
    depends_on:
      - db
    command: /bin/sh -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rastro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: